
import type { Patient } from './types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'P001',
    name: '佐藤 愛子',
    age: 78,
    gender: '女性',
    primaryAilment: '脳梗塞後遺症',
    address: '東京都渋谷区恵比寿1-1-1',
    phone: '090-1234-5678',
    notes: '週3回の訪問看護。リハビリテーションを中心に実施。ご家族の介護負担軽減も課題。',
  },
  {
    id: 'P002',
    name: '鈴木 太郎',
    age: 85,
    gender: '男性',
    primaryAilment: '心不全',
    address: '東京都新宿区西新宿2-8-1',
    phone: '080-8765-4321',
    notes: '呼吸状態のモニタリングと内服管理が重要。塩分制限の食事指導も行っている。',
  },
  {
    id: 'P003',
    name: '高橋 花子',
    age: 67,
    gender: '女性',
    primaryAilment: '糖尿病性神経障害',
    address: '神奈川県横浜市中区日本大通1',
    phone: '090-1122-3344',
    notes: '血糖コントロールとフットケアが中心。インスリン自己注射の指導済み。',
  },
  {
    id: 'P004',
    name: '田中 実',
    age: 72,
    gender: '男性',
    primaryAilment: 'パーキンソン病',
    address: '千葉県千葉市中央区市場町1-1',
    phone: '080-5566-7788',
    notes: '歩行訓練と嚥下機能の評価を定期的に実施。服薬タイミングの管理が課題。',
  },
  {
    id: 'P005',
    name: '渡辺 久美子',
    age: 81,
    gender: '女性',
    primaryAilment: '認知症',
    address: '埼玉県さいたま市浦和区高砂3-15-1',
    phone: '090-9988-7766',
    notes: '徘徊リスクあり。コミュニケーションを密にし、精神的安定を図る。ご家族へのサポートも実施。',
  },
  {
    id: 'P006',
    name: '伊藤 健太',
    age: 65,
    gender: '男性',
    primaryAilment: 'COPD',
    address: '東京都世田谷区世田谷4-21-27',
    phone: '080-1234-9876',
    notes: '在宅酸素療法中。呼吸リハビリと感染予防指導が中心。',
  },
  {
    id: 'P007',
    name: '山本 由紀',
    age: 90,
    gender: '女性',
    primaryAilment: '老衰',
    address: '神奈川県川崎市川崎区宮本町1',
    phone: '090-8765-1234',
    notes: 'ターミナルケア。疼痛管理と精神的ケアを重視。ご家族の意思決定を支援。',
  },
];
